// get products
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

// put products
export const PUT_PRODUCTS_REQUEST = "PUT_PRODUCTS_REQUEST";
export const PUT_PRODUCTS_SUCCESS = "PUT_PRODUCTS_SUCCESS";
export const PUT_PRODUCTS_FAILURE = "PUT_PRODUCTS_FAILURE";

export const POST_PRODUCTS_REQUEST = "POST_PRODUCTS_REQUEST";
export const POST_PRODUCTS_SUCCESS = "POST_PRODUCTS_SUCCESS";
export const POST_PRODUCTS_FAILURE = "POST_PRODUCTS_FAILURE";

export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";