export const GET_PRODUCT_BY_CODE_REQUEST = "GET_PRODUCT_BY_CODE_REQUEST";
export const GET_PRODUCT_BY_CODE_SUCCESS = "GET_PRODUCT_BY_CODE_SUCCESS";
export const GET_PRODUCT_BY_CODE_FAILURE = "GET_PRODUCT_BY_CODE_FAILURE";

export const POST_SALES_REQUEST = "POST_SALES_REQUEST";
export const POST_SALES_SUCCESS = "POST_SALES_SUCCESS";
export const POST_SALES_FAILURE = "POST_SALES_FAILURE";

export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const UPDATE_SALE_ITEM_PRODUCT = "UPDATE_SALE_ITEM_PRODUCT";
export const CLEAR_SALE_ERROR = "CLEAR_SALE_ERROR";
export const CLEAR_SALE = "CLEAR_SALE";